version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm start

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: seabnb
    ports:
      - '3306:3306'
    volumes:
    - ./seabnb.sql:/docker-entrypoint-initdb.d/seabnb.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
