# version: '3.1'

# services:
#   dbMysql:
#     image: mysql:8.0.3
#     restart: always
#     environment:
#         MYSQL_ROOT_PASSWORD: 12345
#         MYSQL_DATABASE: seabnb

#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080